#!/bin/zsh

set -o allexport
source .env set
set +o allexport

cat<<EOL | mongosh "${MONGO_CONNECTION_STR}"
use ${MONGO_DATABASE};
db.getCollection('plans').drop();
db.getCollection('episodic').drop();
EOL

./praxeum stop

rm -rf ${PRAXEUM_DATA_DIR}/*.yaml

./praxeum apply src/praxeum/concept/basic_deployment/*.yaml src/praxeum/knowledge-packs/*.yaml src/praxeum/systemWorkers/*.yaml
./praxeum start
