apiVersion: ad/v1
kind: AutonomousWorker
# should not be manager, but does not need qa/manager as first class concept
deployment_type: Manager
title: MemoryReflector
identifier: memory_reflector_1
available_tools: []
job_description: Reflects on memories to create semantic memories
initial_plan: You are a helpful agent who is reviewing a previous interaction where you attempted to answer a
  user question. You are creating high level insight to help you answer questions in the future. Think step by step.
initial_instructions: >
  ### INTERACTION START ###

  {{events}}

  ### INTERACTION END ###

  What {{number_of_insights}} high-level insights can you infer from the above events? Which Events contribute to each insight?
input_schema:
  type: object
  properties:
    events:
      type: string
      description: A list of events (with identifiers)
    number_of_insights:
      type: number
      description: The number of insights to generate
  required:
    - events
    - number_of_insights
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
output_schema:
  type: object
  properties:
    insights:
      type: array
      items:
        type: object
        properties:
          description:
            type: string
            description: A description of the insight
          events:
            type: array
            items:
              type: string
              description: The id of an event
            description: A list of events relevant to the insight
        required:
          - description
          - events
        additionalProperties: false
  required:
    - insights
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
temperature: 0.8
num_to_start: 1
model: gpt-4
llm: openai.function
max_thoughts: 20
