apiVersion: ad/v1
kind: Deployment
deployment_type: BuiltinFunction
title: concept_details_and_sample
identifier: concept_details_and_sample_alpha
function_name: ConceptFunctions.getDetailsWithSample
job_description: Returns the description and properties of an object. It also
  returns 5 sample rows of data.
input_schema:
  type: object
  properties:
    concept_identifier:
      type: string
      description: The instance name of the concept to get the detail of. Must be a
        valid javascript identifier
    concept_type:
      type: string
      description: The type of the new concept we are building.  Must be one of
        RootConcept or DerivedConcept based on the concept type that is being
        created or edited
  required:
    - concept_identifier
    - concept_type
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
output_schema:
  type: object
  properties:
    concept:
      type: string
      description: A string describing details for the requested concept with sample rows
  required:
    - concept
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
num_to_start: 1
available_tools: []
