apiVersion: ad/v1
kind: AgentTemplate
title: concept_producer_template
producer_class:
  module: @/praxeum/concept/ConceptAgentBuilder
  class: ConceptAgentBuilder
options:
  worker:
    llm: openai.function
    model: gpt-3.5-turbo-16k
    temperature: 0.2
  manager:
    llm: openai.function
    model: gpt-4
    temperature: 0.2
  qa:
    llm: openai.function
    model: gpt-4
    temperature: 0.2
