apiVersion: ad/v1
kind: AutonomousWorker
deployment_type: SkilledWorker
title: define_new_concept
identifier: alpha
job_description: Defines the necessary components of a new concept.
initial_plan: You are a helpful agent answering questions about the creation of
  a new concept which is represented by an interface in our system. Use the set
  of given tools to completely answer the users question in detail.
initial_instructions: >
  You are an agent finding information about concepts in a {{__context__.system}},
  specifically for the {{__context__.process}} process.
    Given the brand new concept {{concept_name}} and it's definition:
    {{concept_definition}}

  You need to find the following to define the new concept:
    1. You need to find the base concept this concept will derive from using the provided description. 
    2. You need to find the properties for the new concept.  Be absolutely certain you use the base concept found from step 1.
    2. You need to find the constraint_query for the new concept. Be absolutely certain you use the base concept found from step 1.
    3. You need to create a very detailed definition definition of the concept. The definition should contain the details for a concept, how it is used, and how it relates to the key concepts in a {{__context__.system}} system for the {{__context__.process}} process.

  Define the new concept.


  Let's think aloud step by step
input_schema:
  type: object
  properties:
    concept_name:
      type: string
      description: The name of the concept to define. Eg, Opportunity
    concept_definition:
      type: string
      description: The definition of the concept to define.
  required:
    - concept_name
    - concept_definition
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
output_schema:
  type: object
  properties:
    concept:
      type: object
      properties:
        concept_identifier:
          type: string
          description: A legal javascript identifier for the new concept
        concept_definition:
          type: string
          description: The definition of the concept to use
        friendly_name:
          type: string
          description: A human readable name for the new concept
        base_concept:
          type: string
          description: The base concept identifier
        constraint_query:
          type: string
          description: A query that constrains and maps this concept to the base concept.
        properties:
          type: array
          items:
            type: object
            properties:
              property_name:
                type: string
                description: The name of the property. The name must be a legal javascript
                  identifier starting with a lower case character
              friendly_name:
                type: string
                description: A human readable name of the property
              description:
                type: string
                description: A detailed description of the property
              type:
                type: string
                description: The type of the property.
            required:
              - property_name
              - friendly_name
              - description
              - type
            additionalProperties: false
      required:
        - concept_identifier
        - concept_definition
        - friendly_name
        - base_concept
        - constraint_query
        - properties
      additionalProperties: false
      description: The concept to return. Return as much of the definition as you can
        based on how much you processed
  required:
    - concept
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
available_tools:
  - find_base_concept
  - find_concept_properties
  - find_concept_constraints_query
  - basic_manager
  - concept_qa
temperature: 0.2
num_to_start: 1
manager: basic_manager
qaManager: concept_qa
model: gpt-3.5-turbo-16k
llm: openai.function
