apiVersion: ad/v1
kind: AutonomousWorker
deployment_type: SkilledWorker
title: find_base_concept
identifier: alpha
job_description: Finds the correct base concept to extend.
initial_plan: You are a helpful tool finding the best possible base object to extend from.
initial_instructions: >
  Given the brand new concept {{concept_name}} and it's definition:

  {{concept_definition}}

  Find the best object to extend from. The best object will be one that matches the definition of the concept passed in. 
  Pay close attention to the properties of the base object and how they map to the concept definition.
  Pay close attention to the grain of each object and if it matches the grain of the concept passed in.

  You will find the best object to extend from by executing the following plan:
    1) Call the 'list_concepts' tool to list the base objects that exist in the system. This tool returns an interface where the interface name is the base object name. You should consider ALL interfaces including the interfaces that start with "table_"
    2) Think, out loud, and list the object names in the list.
    3) Think, out loud, and rate each base object and access the likelihood the object is a match to be this concepts base object. Rate from 0, being the worst, to 1, being the best Order the base objects from best to worst. The best base object MUST be of the same grain as this concept.
    4) Think, out loud, and verify the objects you chose are in the list.
    5) Think, out loud, and choose the best 2-5 base objects and call the tool 'concept_details' to get the details of each. You MUST pass the name of the base object to this tool.
    6) Think, out loud, and from the definitions of these base objects, choose the best match to be this concept's base object.
    7) Write down the NAME of the base object you chose
    7) Return the base object name.

  Let's think aloud step by step. Make sure to record your thoughts
input_schema:
  type: object
  properties:
    concept_name:
      type: string
      description: The name of the concept
    concept_definition:
      type: string
      description: A very detailed definition of the concept
  required:
    - concept_name
    - concept_definition
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
output_schema:
  type: object
  properties:
    base_object_name:
      type: string
      description: "The name of the base object that was chosen as the best candidate"
  required:
    - base_concept
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
available_tools:
  - list_concepts
  - concept_details
  - basic_manager
  - concept_qa
temperature: 0.2
num_to_start: 1
manager: basic_manager
qaManager: concept_qa
model: gpt-3.5-turbo-16k
llm: openai.function
