apiVersion: ad/v1
kind: AutonomousWorker
deployment_type: SkilledWorker
title: find_concept_properties
identifier: alpha
job_description: Finds the optimal set of properties for a concept and maps that concept to a base class.
initial_plan: You are a functional agent who's job is to create an object mapping for a concept.
initial_instructions: |
  Your job is to alter the properties of this concept by mapping the base object to this concept. 

  The current concept is {{concept_name}}.
  It extends from {{base_object_name}}.

  Your plan is to:
    1) Load definition of the base object.
    2) Load the definition of the current object.
    3) Load the query interfaces.
    4) Perform the steps given in the following request:
    {{request}}
  
  
  Let's think aloud step by step. Make sure you record your thoughts at every step.
input_schema:
  type: object
  properties:
    concept_name:
      type: string
      description: The name of the concept. This is usually represented as the interface name of the object
    base_object_name:
      type: string
      description: The name of the base concept object.
    request:
      type: string
      description: The plan this tool should use to execute the request
  required:
    - concept_name
    - base_object_name
    - request
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
output_schema:
  type: object
  properties:
    properties:
      type: array
      items:
        type: object
        properties:
          property_name:
            type: string
            description: The name of the property. The name must be a legal javascript
              identifier starting with a lower case character
          friendly_name:
            type: string
            description: A human readable name of the property
          description:
            type: string
            description: A detailed description of the property
          type:
            type: string
            description: The type of the property.
          reason:
            type: string
            description: The reason why this property is on the property and why it should
              be kept
          should_drop:
            type: boolean
            description: Should this property be dropped or kept on the concept
        required:
          - property_name
          - friendly_name
          - description
          - type
          - reason
          - should_drop
        additionalProperties: false
    constraint_query:
      type: string
      description: The constraint query that maps this concept to the base concept
  required:
    - constraint_query
    - properties
  additionalProperties: false
  $schema: http://json-schema.org/draft-07/schema#
available_tools:
  - concept_query_interfaces
  - concept_details
  - basic_manager
  - concept_qa
temperature: 0.2
num_to_start: 1
manager: basic_manager
qaManager: concept_qa
model: gpt-3.5-turbo-16k
llm: openai.function
upgrade_llm_thought_threshold: 5
max_thoughts: 10
